/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.SystemAdminOps;

import Business.Ecosystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Harshada
 */
public class ManageEnterprisePanel extends javax.swing.JPanel {

    private int isEnterpriseAvailable = 0;
    private JPanel userContainer;
    private Network net;
    private Ecosystem system;

    /**
     * Creates new form ManageEnterprisePanel
     *
     * @param userProcessContainer
     * @param system
     */
    public ManageEnterprisePanel(JPanel userProcessContainer, Ecosystem system) {
        initComponents();
        this.system = system;
        this.userContainer = userProcessContainer;
        populateComboBox();
        populateTableEnterprise();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEnterprise = new javax.swing.JTable();
        lblNetwork = new javax.swing.JLabel();
        lblEnterpriseType = new javax.swing.JLabel();
        lblEnterpriseName = new javax.swing.JLabel();
        txtEnterpriseName = new javax.swing.JTextField();
        btnCreateEnterprise = new javax.swing.JButton();
        comboNetwork = new javax.swing.JComboBox();
        comboEnterpriseType = new javax.swing.JComboBox();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBack.setText("BACK");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 120, 40));

        tblEnterprise.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Network", "Enterprise Name", "Enterprise Type"
            }
        ));
        jScrollPane1.setViewportView(tblEnterprise);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 508, 285));

        lblNetwork.setText("Network");
        add(lblNetwork, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 380, 139, 36));

        lblEnterpriseType.setText("Enterprise Type");
        add(lblEnterpriseType, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 430, 139, 35));

        lblEnterpriseName.setText("Enterprise Name");
        add(lblEnterpriseName, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 480, 166, 36));
        add(txtEnterpriseName, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 480, 211, -1));

        btnCreateEnterprise.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/images/imgSave.png"))); // NOI18N
        btnCreateEnterprise.setText("CREATE  ENTERPRISE");
        btnCreateEnterprise.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateEnterpriseActionPerformed(evt);
            }
        });
        add(btnCreateEnterprise, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 550, -1, 48));

        comboNetwork.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        add(comboNetwork, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 380, 211, 35));

        comboEnterpriseType.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        add(comboEnterpriseType, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 430, 211, 35));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userContainer.remove(this);
        Component[] trackComponent = userContainer.getComponents();
        Component eachComponent = trackComponent[trackComponent.length - 1];
        SystemAdminOperations sysAdminOps = (SystemAdminOperations) eachComponent;
        CardLayout cardLayout = (CardLayout) userContainer.getLayout();
        cardLayout.previous(userContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnCreateEnterpriseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateEnterpriseActionPerformed
        // TODO add your handling code here:
        Network network = (Network) comboNetwork.getSelectedItem();
        Enterprise.EnterpriseType enterprisetype = (Enterprise.EnterpriseType) comboEnterpriseType.getSelectedItem();
        if (network == null || enterprisetype == null) {
            JOptionPane.showMessageDialog(null, "Invalid Input!");
            return;
        }
        if (txtEnterpriseName.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please enter valid input in all fields", "Warining", JOptionPane.WARNING_MESSAGE);
            return;
        }
        String name = txtEnterpriseName.getText();
        Enterprise enterprise = network.getEnterpriseDirectory().createAndAddEnterprise(name, enterprisetype);

        JOptionPane.showMessageDialog(this, "Enterprise has been added Successfully");

        populateTableEnterprise();
        txtEnterpriseName.setText("");

    }//GEN-LAST:event_btnCreateEnterpriseActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCreateEnterprise;
    private javax.swing.JComboBox comboEnterpriseType;
    private javax.swing.JComboBox comboNetwork;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblEnterpriseName;
    private javax.swing.JLabel lblEnterpriseType;
    private javax.swing.JLabel lblNetwork;
    private javax.swing.JTable tblEnterprise;
    private javax.swing.JTextField txtEnterpriseName;
    // End of variables declaration//GEN-END:variables

    private void populateComboBox() {
        comboEnterpriseType.removeAllItems();
        comboNetwork.removeAllItems();

        for (Network network : system.getNetworkList()) {
            comboNetwork.addItem(network);
        }
        for (Enterprise.EnterpriseType type : Enterprise.EnterpriseType.values()) {
            comboEnterpriseType.addItem(type);
        }

    }

    private void populateTableEnterprise() {
        DefaultTableModel model = (DefaultTableModel) tblEnterprise.getModel();

        model.setRowCount(0);
        for (Network network : system.getNetworkList()) {
            for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
                Object[] row = new Object[3];
                row[0] = network.getNetworkName();
                row[1] = enterprise.getName();
                row[2] = enterprise.getEnterpriseType().getValue();

                model.addRow(row);
            }
        }
    }
}
