/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.StoreManager;

import Business.Ecosystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Harshada
 */
public class ManageStoreOperationsPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageStoreOperationsPanel
     */
    
     JPanel userContainer;
     private Ecosystem system;
     private UserAccount account;
     private Organization organization;
     private Enterprise enterprise;
     private UserAccount userAcc;
     
    
    public ManageStoreOperationsPanel(JPanel userContainer, Enterprise enterprise, Organization organization, UserAccount account, Ecosystem system, Network network) {
        initComponents();
        this.userContainer = userContainer;
        this.account=account;
        this.organization=organization;
        this.enterprise=enterprise;
        this.system=system;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        manageOrdersBtn = new javax.swing.JButton();
        manageInventoryBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        kGradientPanel1.setkEndColor(new java.awt.Color(204, 204, 204));
        kGradientPanel1.setkStartColor(new java.awt.Color(0, 153, 0));
        kGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        manageOrdersBtn.setText("Manage Orders");
        manageOrdersBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageOrdersBtnActionPerformed(evt);
            }
        });
        kGradientPanel1.add(manageOrdersBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 320, 230, 50));

        manageInventoryBtn.setText("Manage Stock");
        manageInventoryBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageInventoryBtnActionPerformed(evt);
            }
        });
        kGradientPanel1.add(manageInventoryBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 220, 226, 50));

        jLabel1.setText("MANAGE STORE OPERATIONS");
        kGradientPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 80, -1, 49));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 801, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 598, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void manageInventoryBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageInventoryBtnActionPerformed
        try {
            ManageStockPanel panel = new ManageStockPanel(userContainer,organization,system,enterprise,account);
        userContainer.add("ManageStockPanel", panel);
        CardLayout layout = (CardLayout) userContainer.getLayout();
        layout.next(userContainer);
        }
        
        catch(Exception e)
        {
             JOptionPane.showMessageDialog(this, "Please try again");
        }
    }//GEN-LAST:event_manageInventoryBtnActionPerformed

    private void manageOrdersBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageOrdersBtnActionPerformed
       try {
           ManageOrdersPanel panel = new ManageOrdersPanel(userContainer,organization, system,enterprise,account);
       
        userContainer.add("ManageOrdersJPanel", panel);
        CardLayout layout = (CardLayout) userContainer.getLayout();
        layout.next(userContainer);
       }
       catch(Exception e)
        {
             JOptionPane.showMessageDialog(this, "Please try again");
        }
       
    }//GEN-LAST:event_manageOrdersBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JButton manageInventoryBtn;
    private javax.swing.JButton manageOrdersBtn;
    // End of variables declaration//GEN-END:variables
}
